### PR TITLE
Added Datastore traversal

### PR DESCRIPTION
**Pull request by psav**
Added Datastore traversal

### CODE REVIEW

**Comment by jkinred** [comment]
Thanks @psav. Merged!

**Comment by psav** [comment]
@jkinred No no! Thank you! When can this be expected to be in a release?

**Comment by jkinred** [comment]
I'm really thinking about what to do with psphere. I created it some years ago because there were no Python bindings.

Since then VMware has come out with pyvmomi which is the officially supported Python bindings.

pyvmomi isn't "pythonic" and I have thought about porting psphere over to pyvmomi to provide a pythonic object-oriented wrapper.

Thoughts?

**Comment by psav** [comment]
Obviously it'd be great to be using the official SDK in some regards, obviously because it's going to have more support behind it. We currently use psphere to provide a single pane abstraction API into multiple systems that we use to test ManageIQ.

For me, we are not doing huge tasks in psphere, but we do do some fairly specific ones which psphere helps us to achieve well. I guess basing it on top of the official bindings could allow you to care less about the internals and have a smaller maintenance task because you yourself would have a layer of abstraction there?

**Pull request merged**
